main/views/auth.py
from flask import Blueprint, redirect, render_template, flash, session, url_for
from main.models import User
from main.views.forms import SignupForm, LoginForm
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import current_user, login_user, login_required, logout_user
from main.views import db, login_manager


# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    """
    User sign-up page.

    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    if current_user.is_authenticated:
        flash('You have already registered.')
        if current_user.is_admin():
            return redirect(url_for('admin_bp.show_admin_dashboard'))
        return redirect(url_for('user_bp.show_user_dashboard', uid=current_user.id))
    form = SignupForm()
    print(form.csrf_token)
    if form.validate_on_submit():
        print(form.csrf_token)
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                email=form.email.data,
                password_hash=generate_password_hash(form.password.data)
            )
            if form.email.data == "another.history.team@gmail.com":
                user.access = 2
            db.session.add(user)
            db.session.commit()  # Create new user
            return redirect((url_for('auth_bp.login')))
        flash('A user already exists with that email address.')
    return render_template('register.html', form=form)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        if current_user.is_admin():
            return redirect(url_for('admin_bp.show_admin_dashboard'))
        else:
            return redirect(url_for('user_bp.show_user_dashboard', uid=current_user.id))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password_hash, form.password.data):
            login_user(user)
            session['email'] = form.email.data
            if user.access == 1:
                return redirect(url_for('user_bp.show_user_dashboard', uid=user.id))
            else:
                return redirect(url_for('admin_bp.show_admin_dashboard'))
        flash('Invalid email/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template('sign_in.html', form=form)


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users."""
    flash('Please login to view this page.')
    return redirect(url_for('auth_bp.login'))

@auth_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

main/views/public.py
from flask import Blueprint, redirect, render_template, url_for
from main.models import Course, Module, Book
from sqlalchemy import func
from flask_login import current_user

public_bp = Blueprint('public_bp', __name__)


@public_bp.route('/', methods=['GET', 'POST'])
def index():
    '''popular_courses = Course.query.join(
        CourseLike, Course.id == CourseLike.course_id).group_by(Course.id).order_by(func.count().desc()).limit(3).all()
    popular_courses = [course.title for course in popular_courses]'''

    courses = Course.query.all()

    '''if current_user.is_authenticated:
        return redirect(url_for('user_bp.show_user_dashboard'))'''

    return render_template('index.html', courses=courses)


'''@public_bp.route('/courses', methods=['GET', 'POST'])
def browse_courses():
    course = Course.query.all()
    return render_template('course.html', courses=courses)'''


@public_bp.route('/courses/<int:cid>', methods=['GET', 'POST'])
def show_course(cid):
    course = Course.query.filter_by(id=cid).one()
    modules = Module.query.join(Course, Module.course_id == Course.id).filter(Module.course_id == cid).all()
    books = Book.query.join(Course, Book.course_id == Course.id).filter(Book.course_id == cid).all()
    return render_template("course.html", course=course,
                           modules=modules,
                           books=books)


@public_bp.route('/about', methods=['GET'])
def about_us():
    return render_template("about.html")

main/views/user.py
from flask import Blueprint, redirect, render_template, url_for, flash, request
from flask_login import login_required
from main.models import Course, User, Enrolment, CourseLike, CourseCompletion
from main.views import db
from main.models import ACCESS
from main.decorators import requires_access_level

user_bp = Blueprint('user_bp', __name__)


@user_bp.route('/user/<int:uid>', methods=['GET', 'POST'])
@login_required
@requires_access_level(ACCESS['user'])
def show_user_dashboard(uid):
    user = User.query.filter_by(id=uid).one()
    current_courses = Course.query.join(Enrolment, Course.id == Enrolment.course_id).join(
        User, Enrolment.user_id == User.id).filter(User.id == uid).all()
    liked_courses = Course.query.join(CourseLike, Course.id == CourseLike.course_id).join(
        User, CourseLike.user_id == User.id).filter(User.id == uid).all()
    completed_courses = Course.query.join(CourseCompletion, Course.id == CourseCompletion.course_id).join(
        User, CourseCompletion.user_id == User.id).filter(User.id == uid).all()
    return render_template('login.html', current_courses=current_courses,
                           liked_courses=liked_courses, completed_courses=completed_courses)


'''@user_bp.route('user/<int:user_id>/community_submission', methods=['GET', 'POST'])
@login_required
def community_submission(user_id):

    form = CommunitySubmissionForm()
    if form.validate_on_submit():
        submission = CommunitySubmission(
            user_id=user_id,
            new_course=form.new_course.data,
            select_course=form.select_course.data,
            change_course=form.change_course.data
        )
        db.session.add(submission)
        db.session.commit()
        flash('Your submission has been recorded.')
        return redirect(url_for('.show_user_dashboard'))

    return render_template('submission.html')'''


@user_bp.route('/user/<int:uid>/like/<int:cid>/<action>')
@login_required
@requires_access_level(ACCESS['user'])
def like_action(uid, cid, action):
    course = Course.query.filter_by(id=cid).first_or_404()
    user = User.query.filter_by(id=uid).first()
    if action == 'like':
        user.like_course(course)
        db.session.commit()
    if action == 'unlike':
        user.unlike_course(course)
        db.session.commit()
    return redirect(request.referrer)


@user_bp.route('/user/<int:uid>/enrol/<int:cid>/<action>')
@login_required
@requires_access_level(ACCESS['user'])
def enrol_action(uid, cid, action):
    course = Course.query.filter_by(id=cid).first_or_404()
    user = User.query.filter_by(id=uid).first()
    if action == 'enrol':
        user.enrol(course)
        db.session.commit()
    return redirect(request.referrer)


@user_bp.route('/user/<int:uid>/complete/<int:cid>/<action>')
@login_required
@requires_access_level(ACCESS['user'])
def complete_action(uid, cid, action):
    course = Course.query.filter_by(id=cid).first_or_404()
    user = User.query.filter_by(id=uid).first()
    if action == 'complete':
        user.mark_course_completed(course)
        db.session.commit()
    return redirect(request.referrer)


main/templates/course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta content="" name="description">
    <meta content="" name="author">
    <link href="../../favicon.ico" rel="icon">

    <title>Another History</title>

    <!-- Bootstrap core CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">-->

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Gudea:ital,wght@0,400;0,700;1,400&display=swap"
          rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">
    <div class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="collapse navbar-collapse" id="publicIndex">
                <nav class="mr-auto p-2">
                    <a class="navbar-brand" href="{{ url_for('public_bp.index') }}"><b>Another History</b></a>
                </nav>
                {% if current_user.is_authenticated %}
                <nav class="p-2">
                    <a class="navbar-brand" href="{{ url_for('auth_bp.logout') }}">Log Out</a>
                </nav>

                {% if current_user.is_admin() %}
                <nav class="p-2">
                    <a class="btn btn-primary" href="{{ url_for('admin_bp.show_admin_dashboard') }}"
                       role="button">
                        <svg class="bi bi-person-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
                                  fill-rule="evenodd"/>
                        </svg>
                    </a>
                </nav>
                {% else %}
                <nav class="p-2">
                    <a class="btn btn-primary" href="{{ url_for('user_bp.show_user_dashboard', uid=current_user.id) }}"
                       role="button">
                        <svg class="bi bi-person-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
                                  fill-rule="evenodd"/>
                        </svg>
                    </a>
                </nav>
                {% endif %}

                {% else %}
                <nav class="p-2">
                    <a class="navbar-brand" href="{{ url_for('auth_bp.login') }}">Sign in</a>
                </nav>
                {% endif %}
            </div>
        </nav>
    </div>
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>

    <div class="jumbotron">
        <h1>{{ course.title }}</h1>
    </div>


    <div class="row marketing">
        <div class="card">
            <div class="card-header">
                {{ course.category }}
            </div>
            <div class="card-body">
                <h5 class="card-title">Summary of course</h5>
                <p class="card-text">
                    {{ course.summary }}
                </p><br>
                <p class>
                    <svg class="bi bi-alarm-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M6 .5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H9v1.07a7.001 7.001 0 0 1 3.274 12.474l.601.602a.5.5 0 0 1-.707.708l-.746-.746A6.97 6.97 0 0 1 8 16a6.97 6.97 0 0 1-3.422-.892l-.746.746a.5.5 0 0 1-.707-.708l.602-.602A7.001 7.001 0 0 1 7 2.07V1h-.5A.5.5 0 0 1 6 .5zM.86 5.387A2.5 2.5 0 1 1 4.387 1.86 8.035 8.035 0 0 0 .86 5.387zM11.613 1.86a2.5 2.5 0 1 1 3.527 3.527 8.035 8.035 0 0 0-3.527-3.527zM8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z"
                              fill-rule="evenodd"/>
                    </svg>
                    We suggest 6 hours study time a week for this course
                </p>
                <br>
                {% if current_user.is_authenticated %}
                {% if not current_user.has_enrolled(course) %}
                <a class="btn btn-success"
                   href="{{ url_for('user_bp.enrol_action', uid=current_user.id, cid=course.id, action='enrol') }}">Enroll</a>
                {% else %}
                <p>You're enrolled!</p>
                {% endif %}
                {% endif %}

            </div>
            <div class="card-footer">
                {% if current_user.is_authenticated %}
                {% if current_user.has_liked_course(course) %}
                <svg class="bi bi-bookmark-heart" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"
                          fill-rule="evenodd"/>
                    <path d="M8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"
                          fill-rule="evenodd"/>
                </svg>
                <a href="{{ url_for('user_bp.like_action', uid=current_user.id, cid=course.id, action='unlike') }}">Unlike
                    this course</a>
                {% else %}
                <a href="{{ url_for('user_bp.like_action', uid=current_user.id, cid=course.id, action='like') }}">Like
                    this course to save it for later</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>


    <!-- <div class="container_join">
       <blockquote class="blockquote text-left">
         <p class="mb-0">Interesting quote from someone featured on the course</p>
         <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
       </blockquote>
     </div>-->


    <div class="row marketing">
        <div class="accordion" id="accordionExample">
            <div class="card">
                {% for module in modules %}
                <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                        <button aria-controls="collapseOne" aria-expanded="true" class="btn btn-link"
                                data-target="#collapseOne"
                                data-toggle="collapse" type="button">
                            Week {{ module.week_number}} {{ module.name }} +
                        </button>
                    </h5>
                </div>

                <div aria-labelledby="headingOne" class="collapse show" data-parent="#accordionExample"
                     id="collapseOne">
                    <div class="card-body">
                        {{ module.content }}
                        <!--<br><br><a href="signin.html">Start module</a><br><br>
                        <button type="button" class="btn btn-success">Module completed</button>-->
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container_button">
        {% if current_user.is_authenticated %}
        {% if not current_user.has_marked_completed(course) %}
        <a href="{{ url_for('user_bp.complete_action', uid=current_user.id, cid=course.id, action='complete') }}">Mark
            course completed</a>
        {% else %}
        <a class="btn btn-lg btn-success" type="button">Course completed</a>
        {% endif %}
        {% endif %}
    </div>

    <div class="container heading">
        <h2>Suggested reading</h2>
    </div>

    <div class="row marketing">
        {% for book in books %}
        <div class="col-lg-6">
            <h4><a href="{{ book.preview_link }}">{{ book.book_title }}</a></h4>
            <img alt="" class="thumbnail" src="{{ book.thumbnail }}"/>
        </div>
        {% endfor %}

        <!-- <div class="col-lg-6">
           <h4><a href="">Course Name</a></h4>
           <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
         </div>-->
    </div>

    <footer class="footer">
        <p>Another History was made for Code First Girls Diversity hackathon</p>
    </footer>

</div> <!-- /container -->


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!-- JS, Popper.js, and jQuery -->
<script crossorigin="anonymous"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta content="" name="description">
    <meta content="" name="author">
    <link href="../../favicon.ico" rel="icon">

    <title>Another History</title>

    <!-- Bootstrap core CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">-->

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Gudea:ital,wght@0,400;0,700;1,400&display=swap"
          rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">
    <div class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="collapse navbar-collapse" id="publicIndex">
                <nav class="mr-auto p-2">
                    <a class="navbar-brand" href="{{ url_for('public_bp.index') }}"><b>Another History</b></a>
                </nav>
                {% if current_user.is_authenticated %}
                <nav class="p-2">
                    <a class="navbar-brand" href="{{ url_for('auth_bp.logout') }}">Log Out</a>
                </nav>

                {% if current_user.is_admin() %}
                <nav class="p-2">
                    <a class="btn btn-primary" href="{{ url_for('admin_bp.show_admin_dashboard') }}"
                       role="button">
                        <svg class="bi bi-person-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
                                  fill-rule="evenodd"/>
                        </svg>
                    </a>
                </nav>
                {% else %}
                <nav class="p-2">
                    <a class="btn btn-primary" href="{{ url_for('user_bp.show_user_dashboard', uid=current_user.id) }}"
                       role="button">
                        <svg class="bi bi-person-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
                                  fill-rule="evenodd"/>
                        </svg>
                    </a>
                </nav>
                {% endif %}

                {% else %}
                <nav class="p-2">
                    <a class="navbar-brand" href="{{ url_for('auth_bp.login') }}">Sign in</a>
                </nav>
                {% endif %}
            </div>
        </nav>
    </div>

    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>

    <div class="jumbotron">
        <h1>A brighter<br>future is built on<br>
            <b>Another History</b></h1><br><br>
        <p class="lead">
            We are on a mission to shine a light on the histories you’ll struggle to find in classrooms, lecture halls
            and the media. Join a community who want to unlearn, discover and expand their perspective on the world.
        </p>
        <p><h5><a href="{{ url_for('public_bp.about_us') }}">Find out more</a></h5></p>
    </div>

    <div class="container heading">
        <h2>Browse all courses</h2>
    </div>


    <div class="row marketing">
        {% for course in courses %}
        <div class="col-lg-6">
            <h4><a href="{{ url_for('public_bp.show_course', cid=course.id) }}">{{ course.title }}</a></h4>
            <p>{{ course.summary }}</p>
        </div>
        {% endfor %}
        <!--<div class="col-lg-6">
          <h4><a href="">Course Name</a></h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4><a href="">Course Name</a></h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4><a href="">Course Name</a></h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>-->
    </div>

    <div class="container_join">
        <h3><a href="{{ url_for('auth_bp.register') }}">Join today and begin your unlearning journey
            <svg class="bi bi-arrow-right" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                 xmlns="http://www.w3.org/2000/svg">
                <path d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"
                      fill-rule="evenodd"/>
            </svg>
        </a></h3>
    </div>

    <footer class="footer">
        <p>Another History was made for Code First Girls Diversity hackathon</p>
    </footer>

</div> <!-- /container -->


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!-- JS, Popper.js, and jQuery -->
<!--<script crossorigin="anonymous"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>-->
</body>
</html>

main/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Another History</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Gudea:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="container">
        <div class="header clearfix">
          <nav class="navbar navbar-light">
      <a class="navbar-brand" href= "{{ url_for('public_bp.index') }}"><b>Another History</b></a>
    </nav>
    </div>

        <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
         </div>
      

     {% from 'bootstrap/form.html' import render_field %}

      <form method="post">
        {{ form.csrf_token }}
        <h2>Register</h2><br>
        <div class="form-group" style="width: 50%">
          {{ render_field(form.email, class='form-control', placeholder='Enter email') }}
          {{ render_field(form.password, type='password', class='form-control', placeholder='Password') }}

        </div>
        {{ render_field(form.submit) }}
      </form>

      <footer class="footer">
        <p>Another History was made for Code First Girls Diversity hackathon</p>
      </footer>

    </div> <!-- /container -->



    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>